#!/bin/sh
#polybar script to display vpn connection status

status=$(nordvpn status | grep "Status: " | awk '{print $4}')
case "$status" in
"Connected")
	echo ' VPN^' 
	;;
"Disconnected")
	echo ' VPNv'
	;;
esac


